
jobs:
  include:
    - stage: tests
      language: ruby
      script:
        - bundle exec rubocop
        - bundle exec rspec
    - stage: build docker image
      sudo: true
      dist: trusty
      language: bash
      script:
      - docker build -t chef-dbwm .
      - docker images
      - docker tag chef-dbwm gnublin/chef-dbwm
      - docker push gnublin/chef-dbwm
    - stage: docker_tests
      script: docker run --rm gauth/chef-dbwm cat hello.txt
      language: bash
