version: '3'
services:
  web:
    working_dir: /app
    image: gnublin/chef-dbwm
    ports:
      - '127.0.0.1:8081:8081'
    container_name: chef-dbwm
    volumes:
      - ${PWD}/config/development/config.yml:/app/config/development/config.yml
      - ${PWD}/templates:/app/templates
    command: bundle exec rackup -o 0.0.0.0 -p 8081
